### ISSUE TITLE
missing import include

### ISSUE THREAD

**Issue by ravinayag** [bennett39/drf_tutorial#1]
```from django.conf.urls import include```

Add this line in mysite/urls.py file , to avoid 
``` 
    path('', include('myapi.urls')),
NameError: name 'include' is not defined

**Comment by bennett39** [comment]
Hi @ravinayag - see line 2 of the file you mentioned. The import is already there:

```python
from django.urls import path, include
```

Perhaps you somehow removed it while changing the code, but the repo works as currently published
